version: '3'

services:

  app:
    build:
      context: node
    container_name: app
    networks:
      - myNetwork
    volumes: 
      - ./node:/usr/src/app
    tty: true
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    networks:
      - myNetwork
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodeappdb
      - MYSQL_ROOT_PASSWORD=root

  nginx:
    build:
      context: nginx
    container_name: nginx
    networks:
      - myNetwork
    ports:
      - 8080:80

networks:
  myNetwork:
    driver: bridge